name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies for client and server
      - name: Install client dependencies
        run: npm install --prefix client
      - name: Install server dependencies
        run: npm install --prefix server

      # Step 4: Set up MongoDB environment variable
      - name: Set environment variables
        run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      # Step 5: Run client tests
      - name: Run client tests
        run: npm test --prefix client

      # Step 6: Run server tests
      - name: Run server tests
        run: |
          chmod +x server/node_modules/.bin/jest
          npm test --prefix server

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          vercel deploy --prod \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --project-id ${{ secrets.VERCEL_PROJECT_ID }} \
            --org-id ${{ secrets.VERCEL_ORG_ID }}
