name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main  # Ensures deployment after merging to main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies for client and server
      - name: Install client dependencies
        run: npm install --prefix client  # Install client dependencies
      - name: Install server dependencies
        run: npm install --prefix server  # Install server dependencies

      # Step 4: Install Vite if not already installed
      - name: Install Vite
        run: npm install vite --prefix client  # Install Vite in the client directory

      # Step 5: Set up MongoDB environment variable
      - name: Set environment variables
        run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      # Step 6: Install Jest Environment (if not installed already)
      - name: Install Jest Environment
        run: npm install jest-environment-jsdom@29.7.0 --prefix client

      # Step 7: Run client tests (Vite uses Jest or any other testing framework)
      - name: Run client tests
        run: npm test --prefix client  # Run Vite client tests

      # Step 8: Run server tests
      - name: Run server tests
        run: |
          chmod +x server/node_modules/.bin/jest
          npm test --prefix server

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 4: Install Vite (again to ensure it's available in the deploy step)
      - name: Install Vite
        run: npm install vite --prefix client

      # Step 5: Build client for Vercel deployment (Vite build step)
      - name: Build client
        run: |
          cd client
          npm run build  # Vite's build command to create the production-ready build

      # Step 6: Deploy to Vercel with a valid project name
      - name: Deploy to Vercel
        run: |
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --name "my-valid-project-name"
